# Generated by Django 6.0.3 on 2026-03-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexchange', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='complaint',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='to',
        ),
        migrations.AlterField(
            model_name='registration',
            name='image',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
